/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ActionService } from "../action.service";
import { ActionCreateInput } from "./ActionCreateInput";
import { Action } from "./Action";
import { ActionFindManyArgs } from "./ActionFindManyArgs";
import { ActionWhereUniqueInput } from "./ActionWhereUniqueInput";
import { ActionUpdateInput } from "./ActionUpdateInput";

export class ActionControllerBase {
  constructor(protected readonly service: ActionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Action })
  async createAction(@common.Body() data: ActionCreateInput): Promise<Action> {
    return await this.service.createAction({
      data: {
        ...data,

        game: data.game
          ? {
              connect: data.game,
            }
          : undefined,

        player: data.player
          ? {
              connect: data.player,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        actionType: true,
        amount: true,

        game: {
          select: {
            id: true,
          },
        },

        player: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Action] })
  @ApiNestedQuery(ActionFindManyArgs)
  async actions(@common.Req() request: Request): Promise<Action[]> {
    const args = plainToClass(ActionFindManyArgs, request.query);
    return this.service.actions({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        actionType: true,
        amount: true,

        game: {
          select: {
            id: true,
          },
        },

        player: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Action })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async action(
    @common.Param() params: ActionWhereUniqueInput
  ): Promise<Action | null> {
    const result = await this.service.action({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        actionType: true,
        amount: true,

        game: {
          select: {
            id: true,
          },
        },

        player: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Action })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAction(
    @common.Param() params: ActionWhereUniqueInput,
    @common.Body() data: ActionUpdateInput
  ): Promise<Action | null> {
    try {
      return await this.service.updateAction({
        where: params,
        data: {
          ...data,

          game: data.game
            ? {
                connect: data.game,
              }
            : undefined,

          player: data.player
            ? {
                connect: data.player,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          actionType: true,
          amount: true,

          game: {
            select: {
              id: true,
            },
          },

          player: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Action })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAction(
    @common.Param() params: ActionWhereUniqueInput
  ): Promise<Action | null> {
    try {
      return await this.service.deleteAction({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          actionType: true,
          amount: true,

          game: {
            select: {
              id: true,
            },
          },

          player: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
