/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Action } from "./Action";
import { ActionCountArgs } from "./ActionCountArgs";
import { ActionFindManyArgs } from "./ActionFindManyArgs";
import { ActionFindUniqueArgs } from "./ActionFindUniqueArgs";
import { CreateActionArgs } from "./CreateActionArgs";
import { UpdateActionArgs } from "./UpdateActionArgs";
import { DeleteActionArgs } from "./DeleteActionArgs";
import { Game } from "../../game/base/Game";
import { Player } from "../../player/base/Player";
import { ActionService } from "../action.service";
@graphql.Resolver(() => Action)
export class ActionResolverBase {
  constructor(protected readonly service: ActionService) {}

  async _actionsMeta(
    @graphql.Args() args: ActionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Action])
  async actions(@graphql.Args() args: ActionFindManyArgs): Promise<Action[]> {
    return this.service.actions(args);
  }

  @graphql.Query(() => Action, { nullable: true })
  async action(
    @graphql.Args() args: ActionFindUniqueArgs
  ): Promise<Action | null> {
    const result = await this.service.action(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Action)
  async createAction(@graphql.Args() args: CreateActionArgs): Promise<Action> {
    return await this.service.createAction({
      ...args,
      data: {
        ...args.data,

        game: args.data.game
          ? {
              connect: args.data.game,
            }
          : undefined,

        player: args.data.player
          ? {
              connect: args.data.player,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Action)
  async updateAction(
    @graphql.Args() args: UpdateActionArgs
  ): Promise<Action | null> {
    try {
      return await this.service.updateAction({
        ...args,
        data: {
          ...args.data,

          game: args.data.game
            ? {
                connect: args.data.game,
              }
            : undefined,

          player: args.data.player
            ? {
                connect: args.data.player,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Action)
  async deleteAction(
    @graphql.Args() args: DeleteActionArgs
  ): Promise<Action | null> {
    try {
      return await this.service.deleteAction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Game, {
    nullable: true,
    name: "game",
  })
  async getGame(@graphql.Parent() parent: Action): Promise<Game | null> {
    const result = await this.service.getGame(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Player, {
    nullable: true,
    name: "player",
  })
  async getPlayer(@graphql.Parent() parent: Action): Promise<Player | null> {
    const result = await this.service.getPlayer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
